login:
  path: /
  defaults: { _controller: AppBundle:Security:login }

logout:
  path: /logout

login_check:
  path: /login_check
  defaults: { _controller: AppBundle:Security:login }
  
index:
    path: /index
    defaults: { _controller: AppBundle:Init:index, _locale: es }
         
newAdmin:
    path: /admin/new
    defaults: { _controller: AppBundle:Admin:new, _locale: es }
    
editAdmin:
    path: /admin/edit/{id}
    defaults: { _controller: AppBundle:Admin:edit, _locale: es }
    requirements:
        id: \d+

deleteAdmin:
    path: /admin/delete/{id}
    defaults: { _controller: AppBundle:Admin:delete, _locale: es }
    requirements:
        id: \d+

showAdmin:
    path: /admin/show/{id}
    defaults: { _controller: AppBundle:Admin:show, _locale: es }
    requirements:
        id: \d+

listAdmin:
    path: /admin/list
    defaults: { _controller: AppBundle:Admin:list, _locale: es }
    
newCamarero:
    path: /camarero/new
    defaults: { _controller: AppBundle:Camarero:new, _locale: es }
    
editCamarero:
    path: /camarero/edit/{id}
    defaults: { _controller: AppBundle:Camarero:edit, _locale: es }
    requirements:
        id: \d+
        
deleteCamarero:
    path: /camarero/delete/{id}
    defaults: { _controller: AppBundle:Camarero:delete, _locale: es }
    requirements:
        id: \d+

showCamarero:
    path: /camarero/show/{id}
    defaults: { _controller: AppBundle:Camarero:show, _locale: es }
    requirements:
        id: \d+

listCamarero:
    path: /camarero/list
    defaults: { _controller: AppBundle:Camarero:list, _locale: es }
            
editCocinero:
    path: /cocinero/edit/{id}
    defaults: { _controller: AppBundle:Cocinero:edit, _locale: es }
    requirements:
        id: \d+
        
showCocinero:
    path: /show/{id}
    defaults: { _controller: AppBundle:Cocinero:show, _locale: es }
    requirements:
        id: \d+
              
listCocinero:
    path: /cocinero/list
    defaults: { _controller: AppBundle:Cocinero:list, _locale: es }

newPlato:
    path: /plato/new
    defaults: { _controller: AppBundle:Plato:new, _locale: es }

editPlato:
    path: /plato/edit/{id}
    defaults: { _controller: AppBundle:Plato:edit }
    requirements:
        id: \d+

deletePlato:
    path: /plato/delete/{id}
    defaults: { _controller: AppBundle:Plato:delete }
    requirements:
        id: \d+

showPlato:
    path: /plato/show/{id}
    defaults: { _controller: AppBundle:Plato:show }
    requirements:
        id: \d+

listPlato:
    path: /plato/list
    defaults: { _controller: AppBundle:Plato:list, _locale: es }

newMesa:
    path: /mesa/new
    defaults: { _controller: AppBundle:Mesa:new, _locale: es }

editMesa:
    path: /mesa/edit/{id}
    defaults: { _controller: AppBundle:Mesa:edit }
    requirements:
        id: \d+

deleteMesa:
    path: /mesa/delete/{id}
    defaults: { _controller: AppBundle:Mesa:delete }
    requirements:
        id: \d+

showMesa:
    path: /mesa/show/{id}
    defaults: { _controller: AppBundle:Mesa:show }
    requirements:
        id: \d+

listMesa:
    path: /mesa/list
    defaults: { _controller: AppBundle:Mesa:list, _locale: es }
    
editComanda:
    path: /comanda/edit/{id}
    defaults: { _controller: AppBundle:Comanda:edit, _locale: es }
    requirements:
        id: \d+
        
searchPedido:
    path: /pedido/search/{fecha}
    defaults: { _controller: AppBundle:Pedido:search, _locale: es }

editPedido:
    path: /pedido/edit/{id}
    defaults: { _controller: AppBundle:Pedido:edit, _locale: es }
    requirements:
        id: \d+

showPedido:
    path: /pedido/show/{id}
    defaults: { _controller: AppBundle:Pedido:show, _locale: es }
    requirements:
        id: \d+

selectPedido:
    path: /pedido/select
    defaults: { _controller: AppBundle:Pedido:select, _locale: es }
    
listPedido:
    path: /pedido/pendiente
    defaults: { _controller: AppBundle:Pedido:pendiente, _locale: es }